# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 鸭梨的博客
subtitle: ''
description: '这里记录鸭梨的学习笔记和成长日记'
keywords: 博客,笔记,学习,日记,分享,日志
author: 孙振兴
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.alexsun.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# 切换高亮插件
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# ================================================================
# 下面的配置用于 fluid 的个性化配置
# 可以根据官方文档：https://hexo.fluid-dev.com/docs/guide/ 进行改变
# ================================================================

# 网页标题、大标题
navbar:
  blog_title: 鸭梨的博客

# 主页
index:
  post_url_target: _self
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  # 打字机
  slogan:
    enable: true
    text: 学习如何去学习
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

# 归档页面
archive:
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 80
  banner_mask_alpha: 0.3

# 分类页面
category:
  enable: true
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 80
  banner_mask_alpha: 0.3

# 标签页面
tag:
  enable: true
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

# 自定义页面
page:
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 80
  banner_mask_alpha: 0.3

# 404 页面
page404:
  enable: true
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 10000

# 关于信息
about:
  avatar: /img/avatar.jpg
  name: "鸭梨"
  intro: "终身学习大学新生"
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Sun-ZhenXing', tip: 'GitHub' }
    - { class: 'iconfont icon-qq-fill', link: 'https://qm.qq.com/cgi-bin/qm/qr?k=OH4ueewx2AEPo-5taXFhdAZ671PsW_3t&noverify=0', tip: 'QQ' }

# 自定义 CSS
custom_css:
  # Mac 样式代码
  - /css/macpanel
  - /css/katex-addon
  - /css/code

# 公式支持
post:
  meta:
    author:
      enable: false
    date:
      enable: true
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
  banner_img: https://pic.rmb.bdstatic.com/bjh/c5037424f200bcd116d67034abfb3425.jpeg
  math:
    enable: true
    specific: true
    engine: katex
  copyright:
    enable: true
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
    license: 'BY-NC-SA'
  toc:
    enable: true
    placement: left
    headingSelector: "h1,h2,h3"
  mermaid:
    enable: true
    specific: true
    options:

# 代码
code:
  copy_btn: true
  # 代码语言
  language:
    enable: true
    default: "TEXT"
  # 代码高亮
  highlight:
    enable: true
    line_number: true
    # Options: highlightjs | prismjs
    lib: "highlightjs"
    highlightjs:
      # See: https://highlightjs.org/static/demo/
      style: "github gist"
      style_dark: "dark"
    prismjs:
      # See: https://prismjs.com/
      style: "default"
      style_dark: "tomorrow night"
      preprocess: false

# 页脚
footer:
  content: '
    <span>Powered by</span> <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <div style="font-size: 0.85rem">
      Copyright 2022 <a href="https://github.com/Sun-ZhenXing" target="_blank"><span>鸭梨</span></a>
    </div>
  '

# # 解决 KaTeX 字体加载问题问题
static_prefix:
  katex: https://cdn.staticfile.org/KaTeX/0.10.2/
  mermaid: https://lib.baomitu.com/mermaid/9.1.1/

# 如果网站是 HTTPS 改为 true
force_https: true
