name: Blog CI/CD

# 触发条件
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install -g hexo-cli
        npm install

    - name: Generate files
      # 编译 markdown 文件
      run: |
        hexo clean
        hexo generate

    - name: Deploy hexo blog
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/Sun-ZhenXing/Sun-ZhenXing.github.io
        PASSWORD: ${{secrets.ACCESS_TOKEN}}
      # 将编译后的博客文件推送到指定仓库
      run: |
        cd ./public && git init && echo "blog.alexsun.top" > CNAME && git add .
        git config user.name "Sun-ZhenXing"
        git config user.email "1006925066@qq.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://$PASSWORD@$GITHUB_REPO" master:master
